services:
  static-tools:
    &static-tools
    build: 
      context: .
      target: static-config
  
  ruff-format:
    <<: *static-tools
    entrypoint: ruff format --check
  
  ruff-check:
    <<: *static-tools
    entrypoint: ruff check .
